version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: prp_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/prp_database"
      JWT_SECRET: "your-super-secret-jwt-key-here"
      JWT_EXPIRES_IN: "7d"
      SUPABASE_URL: "your-supabase-url"
      SUPABASE_ANON_KEY: "your-supabase-anon-key"
      SUPABASE_SERVICE_ROLE_KEY: "your-supabase-service-role-key"
      FEDAPAY_API_KEY: "your-fedapay-api-key"
      FEDAPAY_ENVIRONMENT: "sandbox"
      PORT: 3001
      NODE_ENV: "development"
      FRONTEND_URL: "http://localhost:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  # Frontend
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:3001/api"
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

volumes:
  postgres_data:
